points_balance_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres 
      port: 5432
      dbname: datamart
      schema: datamart
      threads: 8
      connect_timeout: 10